# -*- Makefile -*- Time-stamp: <2011-08-22 19:10:46 ptr>

PDFNAMES = test

test_SRC_TEX = test.tex
# consistency_SRC_FIG = GFS.fig GFSwrite.fig VirtualSync.fig

# compare_SRC_GPLOT = strings.gplot
# compare-streams_SRC_MP = streams.mp

# MetabaseTechnology_EXTRA = DC.pdf
# MetabaseTechnology2_EXTRA = DC.pdf
# Meta_EXTRA = DC.pdf db06-mailsize.pdf


