# -*- Makefile-gmake -*-

LIBNAMES = test2 test3

test2_MAJOR = 0
test2_MINOR = 0
test2_PATCH = 0

test3_MAJOR = 0
test3_MINOR = 0
test3_PATCH = 0

test2_SRC_CC = test2.cc
test3_SRC_CC = test3.cc test31.cc
